### ISSUE TITLE
Can you make an example please? It's very helpful.

### ISSUE THREAD

**Issue by ducpt2** [InspireNL/redux-offline-queue#13]
Can you make an example please? It's very helpful. (with redux-saga, redux-persist and simple way not using them?)

Thank you.

**Comment by RobPando** [comment]
Hey @ducpt2, there are examples in the README with and without all the scenarios. Or do you mean an example project?

**Comment by ducpt2** [comment]
@RobPando Thank you for your feedback.
I try to use README but it doesn't work, so i hope you guys can make one, please?

**Comment by RobPando** [comment]
@ducpt2  I will make an example project and let you know as soon as it up, perhaps it will be clearer than the README. Thank you for bringing this into attention 👍

**Comment by ducpt2** [comment]
@RobPando it will be perfect. Especially step 4, and combine with redux-saga.
Thank you.

**Comment by MarcoPortillo** [comment]
@RobPando Hi RobPando, I like the library but I don't get the README really well, where's the example you talked about?

**Comment by ducpt2** [comment]
@MarcoPortillo  +1 :)

**Comment by RobPando** [comment]
@ducpt2 @MarcoPortillo Sorry for the wait guys. I just created the example project and updated the README with it #14 . Hopefully it helps clarify all doubts, and if you have any questions whatsoever, do let me know.

**Comment by ducpt2** [comment]
@RobPando Thank you so much. I will try it :)
