### ISSUE TITLE
Using plain actions for offline queue

### ISSUE THREAD

**Issue by sharathchandramg** [InspireNL/redux-offline-queue#15]
Hi,
I was just trying to get the basic app running. I am not using redux-sauce and instead using plain objects for actions. 

e.g.

```
export function getFormData(templateId, instanceId) {
	return {
		type: types.GET_FORM_DATA_REQUEST,
		payload: {
			templateId: templateId,
			instanceId: instanceId,
		}
	}
}
```

How can I mark these actions under maskActionOffline?

**Comment by RobPando** [comment]
@sharathchandramg Hey, you have to pass to `markActionOffline` an initial object param containing your actions you want to queue. For your case you would do something like:

```javascript
const Creators = {
  getFormData, // using object literal shorthand
}

markActionsOffline(Creators, ['getFormData'])
```

or simply  `markActionsOffline({ getFormData }, ['getFormData'])` if you are only going to ever have one.
