### ISSUE TITLE
How to add to offline queue? And redux-thunk

### ISSUE THREAD

**Issue by johhansantana** [InspireNL/redux-offline-queue#16]
Hello

How would you go on adding a redux-thunk action to offline queue?

This is my action:
```typescript
export function uploadUserForm(values: any) {
  return async dispatch => {
    try {
      const res = await fetch(`${location.origin}/api/endpoint`, {
        method: "post",
        headers: {
          "content-type": "application/json"
        },
        body: JSON.stringify(values)
      });
      if (!res.ok) {
        throw await res.json();
      }
      await res.json();
    } catch (error) {
      return error;
    }
  };
}
```

Also, my actions look like this:
```typescript
export function setSubmitting(submitting: boolean): SET_SUBMIT {
  return {
    type: "SET_SUBMIT",
    submitting
  };
}
```

How would I add this like in your example:
```javascript
import { markActionsOffline } from 'redux-offline-queue'

const Creators = {
  createBlog: blog => ({
    type: 'CREATE_BLOG',
    blog,
  }),
}

markActionsOffline(Creators, ['createBlog'])
...
```

How does `markActionsOffline` work? Do I have to call it? Is it automatically based on:
```javascript
if (false) {
  reduxStore.dispatch({ type: ONLINE });
} else {
  reduxStore.dispatch({ type: OFFLINE });
}
```

**Comment by RobPando** [comment]
I have not tried to use redux-thunk, I am not sure if it would work, but you can give it a try. follow the README check for the redux-saga implementation and instead of the `createSagaMiddleware` try replacing it with thunk. as for the action in your case you would do something like:
 `markActionsOffline({ setSubmitting }, ['setSubmitting'])`

**Comment by Ann1995** [comment]
@johhansantana Did you manage to set up?
