### ISSUE TITLE
toggling wifi does not trigger ONLINE action

### ISSUE THREAD

**Issue by jasan-s** [InspireNL/redux-offline-queue#27]
If I turn "OFF" the wifi while running in iOS simulator and using React-native-debugger.  The OFFLINE action fires. However, if I turn it back "ON" the ONLINE action does not fire. SEE VIDEO

![redux-offline](https://user-images.githubusercontent.com/13863953/50110250-a1ce3200-01ee-11e9-97cf-f32703836a15.gif)

**Comment by RobPando** [comment]
@jasan-s  Can you try and replicate the behavior on an actual device? I don't believe this would happen on an actual device.

**Comment by jasan-s** [comment]
Not sure how I would test that because turning off wifi will kill the debugger.

**Comment by jasan-s** [comment]
@RobPando  I can confirm it works on Device. tested it on iPhone
